# Generated by Django 4.0.6 on 2022-07-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_link_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(max_length=2000),
        ),
    ]
