# Generated by Django 4.0.6 on 2022-07-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_alter_comment_comment_alter_link_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='link',
            name='state',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
